1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [ ]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)
b=np.sum(a)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [ ]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)
b=a.sum(axis=1)
c=a.sum(axis=0)
print(b)
print(c)


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [ ]:
import numpy as np 
a=np.arange(0,16).reshape(4,4)
print(a)
b=np.min(a)
c=np.max(a)
d=np.mean(a)
print(b)
print(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0
15
7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [ ]:
import numpy as np
a=np.arange(0,100).reshape(10,10)
print(a)
print(a[6])
print(a[3:8])
print(a[5][5])
print(a[:,4])
print(a[:,1:4])


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[60 61 62 63 64 65 66 67 68 69]
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
55
[ 4 14 24 34 44 54 64 74 84 94]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]
