1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [ ]:
 
import numpy as np
a= np.arange(0,9).reshape(3,3)
b= np.arange(0,9).reshape(3,3)
print(a)
print(b)
c=np.dot(a,b)
print(c)
print(np.transpose(c))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  42  69]
 [ 18  54  90]
 [ 21  66 111]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [ ]:
 
import numpy as np
a=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(a)
det=np.linalg.det(a)
print(int(det))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
