1. Generate a 3 x 3 matrix using random module.

In [ ]:
 
import numpy as np
 
array = np.random.randint( 10,size=(3, 3)) 
 
print(array)

[[3 9 6]
 [8 6 6]
 [5 1 6]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [ ]:
 
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print (np.hstack((x,y)))
print (np.vstack((x,y)))

[[6 4 3 4]
 [1 7 9 3]
 [5 7 3 3]
 [2 5 9 7]]
[[7 2 4 7]
 [8 2 7 2]
 [6 7 8 8]
 [8 6 9 1]]
[[6 4 3 4 1 7 9 3 7 2 4 7 8 2 7 2]
 [5 7 3 3 2 5 9 7 6 7 8 8 8 6 9 1]]
[[6 4 3 4 1 7 9 3]
 [5 7 3 3 2 5 9 7]
 [7 2 4 7 8 2 7 2]
 [6 7 8 8 8 6 9 1]]
