1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [4]:
import numpy as np 
a=np.array([[1,2],[3,4]])
print(a)
b=np.array ([[8],[18]])
print(b)
x=np.linalg.solve(a,b)
print(x)


[[1 2]
 [3 4]]
[[ 8]
 [18]]
[[2.]
 [3.]]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [3]:
import numpy as np
a=np.array([2,3,4])
print(a)
x=np.sin(a)
print(x)
y=np.cos(a)
print(y)
z=np.tan(a)
print(z)


[2 3 4]
[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [5]:
import numpy as np
b=np.array([5,6])
print(b)
a=2*np.sin(b)
print(a)
c=2*np.cos(3*b)
print(c)
d=4*np.tan(2*b)
print(d)



[5 6]
[-1.91784855 -0.558831  ]
[-1.51937583  1.32063342]
[ 2.59344331 -2.54343971]
